language: node_js
node_js:
  '12'
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
install:
  - npm install
script:
  - npm run clean
  - npm run build
  - npm test
after_success:
  # run code coverage
  - codecov --token=b1f81701-a627-49b1-a3d9-9d4fdd1ac84b
